// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZEM_ttWf6U5fGP5djSINRGkNltDn1HY8',
    appId: '1:430495886304:web:12ffa2e7087699597a5985',
    messagingSenderId: '430495886304',
    projectId: 'kctrustedcarpool',
    authDomain: 'kctrustedcarpool.firebaseapp.com',
    storageBucket: 'kctrustedcarpool.firebasestorage.app',
    measurementId: 'G-EVKMRLNVN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoFLcFQQMXS6Y7Qa9JWOkkvknKDAAxA9A',
    appId: '1:430495886304:android:1e7a4072ef985c497a5985',
    messagingSenderId: '430495886304',
    projectId: 'kctrustedcarpool',
    storageBucket: 'kctrustedcarpool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvtFMKG8TDMNE45eB6PQlypjxyhCEUQ4w',
    appId: '1:430495886304:ios:2b0952af6ff8d8327a5985',
    messagingSenderId: '430495886304',
    projectId: 'kctrustedcarpool',
    storageBucket: 'kctrustedcarpool.firebasestorage.app',
    iosBundleId: 'com.example.kctrustedcarpool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvtFMKG8TDMNE45eB6PQlypjxyhCEUQ4w',
    appId: '1:430495886304:ios:2b0952af6ff8d8327a5985',
    messagingSenderId: '430495886304',
    projectId: 'kctrustedcarpool',
    storageBucket: 'kctrustedcarpool.firebasestorage.app',
    iosBundleId: 'com.example.kctrustedcarpool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZEM_ttWf6U5fGP5djSINRGkNltDn1HY8',
    appId: '1:430495886304:web:12fa60ba575701657a5985',
    messagingSenderId: '430495886304',
    projectId: 'kctrustedcarpool',
    authDomain: 'kctrustedcarpool.firebaseapp.com',
    storageBucket: 'kctrustedcarpool.firebasestorage.app',
    measurementId: 'G-R5SDHMYS6W',
  );
}
